### PR TITLE
Mocks clean up

### PR DESCRIPTION
**Pull request by Emkas**

### CODE REVIEW

**Comment by Emkas** [comment]
After this PR I will be able to say that I reduced number of warnings by half. (Only 1,2 k left :dancers:)

**Comment by BalusC** [comment]
Build failed after merge:

> Error:  COMPILATION ERROR : 
> [INFO] -------------------------------------------------------------
> Error:  /home/runner/work/mojarra/mojarra/impl/src/test/java/jakarta/faces/component/NamingContainerTestCase.java:[66,48] incompatible types: java.util.Map<capture#1 of ?,capture#2 of ?> cannot be converted to java.util.Map<java.lang.String,java.lang.String>

Can you take a look?

**Comment by Emkas** [comment]
Sure. Sorry, I thought I run `mvn clean install`...

**Comment by Emkas** [comment]
Fixed in #5147.
