### ISSUE TITLE
Endless loop in MultiViewHandler.normalizeRequestURI

### ISSUE THREAD

**Issue by pdudits** [eclipse-ee4j/mojarra#5525]
**Describe the bug**

When FacesServlet is mapped to `/*` or invoked via forwarding where other servlet has this mapping, the view processing never terminates as it is stuck in `while` loop in `MultiViewHandler.normalizeRequestURI`. `mapping` is `""` in this case and therefore loop condition is always true and the `viewId` never changes.

**To Reproduce**

1. Set mapping of `facesServlet` to `/*`
2. Make a request to a view
3. Observe infinite loop

**Expected behavior**

Request processing should terminate. Given that `/*` is rare but valid entry, it shouldn't try any normalization

**Additional context**

Will provide PR for version 4, master is not buildable at this time.

**Comment by BalusC** [comment]
> Will provide PR for version 4

Your PR was for master not 4.0 so I closed it. Please recreate PR for 4.0.

> master is not buildable at this time

Can you please be a bit more specific so we can fix this.

**Comment by pizzi80** [comment]
> > master is not buildable at this time
> 
> Can you please be a bit more specific so we can fix this.

I think that "it's not buildable at this time" means that there is not 
Jakarta Faces API v5.0 jar available on Maven

I've also had problems in the past trying to work on Mojarra v5 
then I've decided to stay on my forked v4 version waiting 
for better times 

I've tons of PR to backport, but I need at least Java 17 (or 21 if possible)

**Comment by BalusC** [comment]
> I think that "it's not buildable at this time" means that there is no Jakarta Faces API v5.0 jar available on Maven

Just pull faces repo as well https://github.com/jakartaee/faces and then checkout 5.0 branch and then `cd api` and then `mvn clean install` from there to build the 5.0 snapshot into your local repo.

**Comment by pizzi80** [comment]
Thanks again for your suggestions, 
but it seems like a development only version

I would like to work on a real 5.0.0 version 
that could be easily deployed with maven

Wich could be a release date for 5.0.0?
I see only a PR that need to be merged ...

**Comment by BalusC** [comment]
https://github.com/jakartaee/faces/milestone/22

**Comment by pdudits** [comment]
Hello, I've redone the PR against 4.0.

As for master not building, regardless if i run it as `mvn clean install` or `mvn -Papi clean install` the compilation fails with:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project mojarra: Compilation failure: Compilation failure:
[ERROR] /C:/src/payara/mojarra/impl/src/main/java/com/sun/faces/el/ELUtils.java:[34,44] cannot find symbol
[ERROR]   symbol:   class ContextParam
[ERROR]   location: @interface jakarta.faces.annotation.FacesConfig
[ERROR] /C:/src/payara/mojarra/impl/src/main/java/com/sun/faces/application/ApplicationAssociate.java:[80,44] cannot find symbol
[ERROR]   symbol:   class ContextParam
[ERROR]   location: @interface jakarta.faces.annotation.FacesConfig
[ERROR] /C:/src/payara/mojarra/impl/src/main/java/com/sun/faces/application/resource/WebappResourceHelper.java:[37,44] cannot find symbol
[ERROR]   symbol:   class ContextParam
[ERROR]   location: @interface jakarta.faces.annotation.FacesConfig
```

**Comment by BalusC** [comment]
> Hello, I've redone the PR against 4.0.

Thanks!

> As for master not building, regardless if i run it as `mvn clean install` or `mvn -Papi clean install` the compilation fails with:

https://github.com/eclipse-ee4j/mojarra/issues/5525#issuecomment-2494370436

**Comment by pizzi80** [comment]
it would be very good! 
In this way I will create my PR(s) directly to 5.0 to let 4.0 and 4.1 remain in maintenance mode
