### ISSUE TITLE
Can't use JSF 2.2.11 in plain Tomcat

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#3950]
I think this is a regression caused by #3778.
If I replace JSF 2.2.10 with 2.2.11 in my web application (which doesn't use CDI at all), I get the following exception at startup:

```
java.lang.NoClassDefFoundError: javax/enterprise/inject/spi/BeanManager
	at com.sun.faces.util.Util.getCdiBeanManager(Util.java:184) ~[javax.faces-2.2.11.jar:2.2.11]
	at com.sun.faces.config.WebConfiguration.processJndiEntries(WebConfiguration.java:858) ~[javax.faces-2.2.11.jar:2.2.11]
	at com.sun.faces.config.WebConfiguration.<init>(WebConfiguration.java:154) ~[javax.faces-2.2.11.jar:2.2.11]
	at com.sun.faces.config.WebConfiguration.getInstance(WebConfiguration.java:214) ~[javax.faces-2.2.11.jar:2.2.11]
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:166) ~[javax.faces-2.2.11.jar:2.2.11]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4770) [catalina.jar:8.0.15]
```

In fact, I don't have that class.
I'm getting Mojarra with Gradle:
<tt>compile "org.glassfish:javax.faces:2.2.11"</tt>
and this doesn't carry in any dependency that contains that class. Also, I don't expect to need it if I don't use CDI (I'm using Spring, by the way).
#### Environment
Plain Tomcat 8, JSF 2.2, Servlet 3.1
#### Affected Versions
[2.2.11]
