### ISSUE TITLE
Mojarra 3.0.2 fails when a tag handler is missing a class.

### ISSUE THREAD

**Issue by larsgrefer** [eclipse-ee4j/mojarra#5041]
We noticed a strange error while working with Mojarra 3.0.2 and Omnifaces 4.0-M12:

The application startup fails with the following error in Mojarra:
```
java.lang.NoClassDefFoundError: jakarta/validation/ConstraintViolation
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504) ~[na:na]
	at com.sun.faces.util.Util.classHasAnnotations(Util.java:1255) ~[jakarta.faces-3.0.2.jar!/:3.0.2]
	at com.sun.faces.application.ApplicationInstanceFactoryMetadataMap.onPut(ApplicationInstanceFactoryMetadataMap.java:54) ~[jakarta.faces-3.0.2.jar!/:3.0.2]
	at com.sun.faces.application.ApplicationInstanceFactoryMetadataMap.onPut(ApplicationInstanceFactoryMetadataMap.java:27) ~[jakarta.faces-3.0.2.jar!/:3.0.2]
	at com.sun.faces.util.MetadataWrapperMap.put(MetadataWrapperMap.java:78) ~[jakarta.faces-3.0.2.jar!/:3.0.2]
	at com.sun.faces.config.processor.AbstractConfigProcessor.loadClass(AbstractConfigProcessor.java:285) ~[jakarta.faces-3.0.2.jar!/:3.0.2]
	at com.sun.faces.config.processor.FaceletTaglibConfigProcessor.processHandlerClass(FaceletTaglibConfigProcessor.java:391) ~[jakarta.faces-3.0.2.jar!/:3.0.2]
	at com.sun.faces.config.processor.FaceletTaglibConfigProcessor.processTags(FaceletTaglibConfigProcessor.java:341) ~[jakarta.faces-3.0.2.jar!/:3.0.2]
	at com.sun.faces.config.processor.FaceletTaglibConfigProcessor.processTagLibrary(FaceletTaglibConfigProcessor.java:276) ~[jakarta.faces-3.0.2.jar!/:3.0.2]
	at com.sun.faces.config.processor.FaceletTaglibConfigProcessor.process(FaceletTaglibConfigProcessor.java:232) ~[jakarta.faces-3.0.2.jar!/:3.0.2]
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:309) ~[jakarta.faces-3.0.2.jar!/:3.0.2]
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:207) ~[jakarta.faces-3.0.2.jar!/:3.0.2]
```

The handler class passed to `com.sun.faces.util.Util.classHasAnnotations` is `org.omnifaces.taghandler.ValidateBean`

Since both Mojarra and Omnifaces list jakarta.validation as an optional dependency and we are neither using `<o:validateBean>` nor `<f:validateBean>`, I'd expect this to not be an error.

I think this exception should be caught somewhere in `FaceletTaglibConfigProcessor`.

**Comment by mnriem** [comment]
Please see if you can reproduce it using only core Mojarra 3.0.2.

**Comment by larsgrefer** [comment]
@mnriem What exactly do you mean with "only core Mojarra"?

This issue arises when an optional dependency (in my case jakarta.validation) of an external tag library (in my case Omnifaces) is not present on the classpath.

**Comment by larsgrefer** [comment]
I've created a small reproducer project here: https://github.com/larsgrefer/mojarra-5041

**Comment by BalusC** [comment]
Yup, point taken, this is indeed unexpected.

I can tell from own experience that it didn't happen in some previous Mojarra version, so it has clearly regressed at some point.

**Comment by BalusC** [comment]
Noted should be that I cannot come up with a simple integration test for this (as long as we keep using GlassFish it is).

**Comment by mnriem** [comment]
@BalusC if this is fixed for 3.0 please close it and create a separate issue for 4.0 linking this issue or add a 4.0 label to this one so it does not get lost.

**Comment by BalusC** [comment]
Sorry, forgot to close this.

Already upmerged in 3.0 https://github.com/eclipse-ee4j/mojarra/commit/e879705f6c535bc13641445b4520f9d60f1e91ab
Already upmerged in 4.0 https://github.com/eclipse-ee4j/mojarra/commit/0c7e33a5a0c7d1ca17ca71dc07fb8f7b7fd55ed0
